### ISSUE TITLE
Name shadowing rule

### ISSUE THREAD

**Issue by krzema12** [neeffect/kure-potlin#16]
Hi @jarekratajski,

I'm wondering what you think about adding a rule that would catch name shadowing in functions:

```kotlin
fun hello(name: String) = run {
    // ... lots of code ...
    val name = "Ble"
    // ... lots of code ...
    "Hello $name!" // which "name" is it? surprise
}

fun main() {
   println(hello("World"))
}
```

(prints `Hello Ble!`)

It breaks referential transparency (as far as I understand it correctly), and to me it's similar to rewriting parameter's value whereas by design they are immutable.

The Kotlin compiler produces a mere warning "Name shadowed: ...", and not every project treats warnings as errors, hence my idea to make it a designated rule.

**Comment by jarekratajski** [comment]
This is part of regular `detekt` rules:
https://detekt.dev/docs/rules/naming/#nonameshadowing
