### ISSUE TITLE
More purity rules

### ISSUE THREAD

**Issue by krzykrucz** [neeffect/kure-potlin#3]
@jarekratajski What do you think about forbidding the usage of such non-functional features of Kotlin as:
* a simple `class`
* an `abstract class`
* throwing exceptions
* usage of mutable collections from stdlib

These rules could be made separate to make them configurable via configuration yaml as in detekt standard.

Do you think it would make sense to create a pull request for any of those things?

**Comment by jarekratajski** [comment]
+++ for no mutable collections 
++ for no throwing of exceptions
+/- for an abstract class - this is an OOP feature, not very safe - but does not mean the code will be  impure (in terms of pure functions),  (I am unsure here)
- for a class - I have a mixed fillings. I do not see the point that just a class  is a wrong thing (for instance it does not have to be worse than data class).

Proposal - lets have a configuration for that (last 2 rules) - so the developer can select features/checks.

**Comment by jarekratajski** [comment]
So - I merged first two rules and published as 2.1 - thank you for this input.
As for classes:
 - I merged it to master  - not published yet- I would like to make it configurable(on/off) (maybe even all rules should be configurable),

**Comment by krzykrucz** [comment]
Thanks! Maybe I'll create a PR to split ImpureCode and OOClass rules to smaller ones and make everything configurable

**Comment by jarekratajski** [comment]
Thanks - for the great contribution. You have made this funny small plugin quite a professional tool now.

I have doubts about "class" and "abstract class"  default active. I would put them on false as default, but I am not sure.

From one side I do not see anything impure in  just having a class, and maybe I even need classes (even open class) in few places (like dependency injection patter I use  here (https://github.com/neeffect/kotlin-stones/blob/master/stones-server/src/main/kotlin/pl/setblack/kstones/stones/StoneModule.kt)  I do not know.

On the other hand, I already tried class rules and indeed most of the classes I have found in my code could be either data classes or functions. 
So - for sure this rule is useful.

Can you elaborate on that?

**Comment by MiSikora** [comment]
One more argument for leaving class rule on false as a default. Sometimes, even with pure value objects, I don't wan't to use `data class` because it exposes a `copy` function which in turn exposes constructor even if it is private. And if creation of a value object can fail I'd like to return an `Either` with a reason instead of crashing or having an improper state.

Arguably I could use something like [no-copy plugin](https://github.com/AhmedMourad0/no-copy) but I don't see any harm in having just `class`.

**Comment by krzykrucz** [comment]
ClassDefinition rule is already disabled by default. I left AbstractClassDefinition enabled by default, because `abstract class` which assumes inheritance is a purely object-oriented feature. Same thing could be said about open classes/functions/properties. In my opinion, even if someone has to use an abstract or open class, they should be annotated with a `@Suppress` annotation.

But I have no problem with disabling by default the AbstractClassDefinition or a potential rule for open functions/properties, as long as they are available. As a matter of fact, it's a detekt standard that all custom rules should be disabled by default, and I recon we keep most enabled out of convenience reasons.

**Comment by jarekratajski** [comment]
Thank you.

Do you @krzykrucz   have any link to this ` it's a detekt standard that all custom rules should be disabled by default,`?
Maybe that is a best option - to let users decide in each case- I just could not find this. 
(and in fact that is just another "issue" - I would close this as I consider it done, :-))

**Comment by krzykrucz** [comment]
@jarekratajski  Maybe it's wrong to say that rules should be disabled by default, but a new rule, if you make it configurable, it's disabled and there is no straightforward way to change it (as you could see in my PR). It is also explained here: https://github.com/detekt/detekt/issues/3244#issuecomment-735365326 

What I also meant, is that most of the predefined rules in detekt are actually disabled by default as you can see for instance here: https://detekt.github.io/detekt/comments.html

**Comment by jarekratajski** [comment]
I see that if you use other plugin - https://detekt.github.io/detekt/formatting.html - then some rules are on some off by default.
Propose:
let's keep it as it is now - flexible with some defaults - where let's say all of us see no controversy. 
after all we just want to see pure code - some of us just have higher expectations when it comes what pure means (I am still learning).
